export const FETCH_PAYMENT_CHECKOUT = 'FETCH_PAYMENT_CHECKOUT'
export const FETCH_PAYMENT_CHECKOUT_SUCCESS = 'FETCH_PAYMENT_CHECKOUT_SUCCESS'
export const FETCH_PAYMENT_CHECKOUT_FAIL = 'FETCH_PAYMENT_CHECKOUT_FAIL'

export const SET_DONATION = 'SET_DONATION'
export const SET_DONATION_NAME = 'SET_DONATION_NAME'
export const SET_DONATION_AMOUNT = 'SET_DONATION_AMOUNT'
export const SET_DONATION_CUSTOM = 'SET_DONATION_CUSTOM'
