export const FETCH_PAYMENT_CHECKOUT = 'FETCH_PAYMENT_CHECKOUT'
export const FETCH_PAYMENT_CHECKOUT_SUCCESS = 'FETCH_PAYMENT_CHECKOUT_SUCCESS'
export const FETCH_PAYMENT_CHECKOUT_FAIL = 'FETCH_PAYMENT_CHECKOUT_FAIL'

export const SET_DONATION = 'SET_DONATION'
