export const FETCH_PAYMENT_CHECKOUT = 'FETCH_PAYMENT_CHECKOUT'
export const FETCH_PAYMENT_CHECKOUT_SUCCESS = 'FETCH_PAYMENT_CHECKOUT_SUCCESS'
export const FETCH_PAYMENT_CHECKOUT_FAIL = 'FETCH_PAYMENT_CHECKOUT_FAIL'

export const SET_DONATION = 'SET_DONATION'
export const SET_DONATION_NAME = 'SET_DONATION_NAME'
export const SET_DONATION_AMOUNT = 'SET_DONATION_AMOUNT'
export const SET_DONATION_CUSTOM = 'SET_DONATION_CUSTOM'

export const FETCH_SUM_DONATION = 'FETCH_SUM_DONATION'
export const FETCH_SUM_DONATION_SUCCESS = 'FETCH_SUM_DONATION_SUCCESS'
export const FETCH_SUM_DONATION_FAIL = 'FETCH_SUM_DONATION_FAIL'

export const FETCH_SUM_PAYMENT = 'FETCH_SUM_PAYMENT'
export const FETCH_SUM_PAYMENT_SUCCESS = 'FETCH_SUM_PAYMENT_SUCCESS'
export const FETCH_SUM_PAYMENT_FAIL = 'FETCH_SUM_PAYMENT_FAIL'

export const FETCH_DONATIONS = 'FETCH_DONATIONS'
export const FETCH_DONATIONS_SUCCESS = 'FETCH_DONATIONS_SUCCESS'
export const FETCH_DONATIONS_FAIL = 'FETCH_DONATIONS_FAIL'